<?php

$profiles = [
    'global_only' => [
        'user' => 'No access.',
        'customer_admin' => 'No access.',
        'admin' => 'No access.',
        'global_admin' => 'Full global management access across all accounts.',
    ],
    'account_admins_only' => [
        'user' => 'No access.',
        'customer_admin' => 'Full management for assigned account data.',
        'admin' => 'Full management for assigned account data.',
        'global_admin' => 'Full global management access across all accounts.',
    ],
    'all_read' => [
        'user' => 'Read-only access within assigned account scope.',
        'customer_admin' => 'Read-only visibility for account-level insights.',
        'admin' => 'Read-only visibility for account-level insights.',
        'global_admin' => 'Read-only visibility across all accounts.',
    ],
    'all_read_with_admin_actions' => [
        'user' => 'Read-only access within assigned account scope.',
        'customer_admin' => 'Can manage account data and execute page actions.',
        'admin' => 'Can manage account data and execute page actions.',
        'global_admin' => 'Can manage all account data and execute all actions.',
    ],
    'all_personal_workspace' => [
        'user' => 'Can create and manage personal estimates/scenarios.',
        'customer_admin' => 'Can create and manage personal estimates/scenarios.',
        'admin' => 'Can create and manage personal estimates/scenarios.',
        'global_admin' => 'Can create and manage personal estimates/scenarios across all accessible data.',
    ],
    'shipment_workspace' => [
        'user' => 'Can review pallets and shipment status, but cannot commit shipment-management actions.',
        'customer_admin' => 'Can create and manage shipments for assigned account.',
        'admin' => 'Can create and manage shipments for assigned account.',
        'global_admin' => 'Can create and manage shipments across all accounts.',
    ],
    'documents_workspace' => [
        'user' => 'Can browse and download documents in scope.',
        'customer_admin' => 'Can browse, download, and upload/manage documents in account scope.',
        'admin' => 'Can browse, download, and upload/manage documents in account scope.',
        'global_admin' => 'Can browse, download, upload, and manage documents across all accounts.',
    ],
];

return [
    'aliases' => [
        'profile_settings' => 'account_settings',
        'cost_analysis' => 'module_cost_analysis',
        'sustainability' => 'sustainability_overview',
        'manage_warehouse_inventory' => 'warehouse',
        'warehouse_info' => 'warehouse',
        'manage_warehouses' => 'warehousing_overview',
        'invoices' => 'invoices_all',
    ],
    'pages' => [
        'dashboard' => [
            'name' => 'Dashboard',
            'description' => 'Portfolio overview with project health, delivery progress, and top-level logistics KPIs.',
            'help' => 'Explain status badges, summarize portfolio health, and direct users to project-level detail pages.',
            'actions' => ['View project cards/table', 'Filter portfolio by health', 'Switch units and view mode'],
            'supporting_pages' => ['project_overview', 'module_cost_analysis', 'warehousing_overview', 'manage_deliveries'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'project_overview' => [
            'name' => 'Project Overview',
            'description' => 'Single-project command center for delivery progress, milestones, costs, and module status.',
            'help' => 'Break down project progress, milestone status, and which next logistics action is needed.',
            'actions' => ['Review project KPIs', 'Open related deliveries/modules/docs', 'Inspect milestones and costs'],
            'supporting_pages' => ['create_shipment', 'scheduling', 'project_photos', 'module_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'add_project' => [
            'name' => 'Add Project',
            'description' => 'Project creation form for site details, MW targets, and operational setup.',
            'help' => 'Guide field completion and explain which setup details impact downstream scheduling and logistics.',
            'actions' => ['Create project record', 'Set site operating constraints', 'Attach initial project inputs'],
            'supporting_pages' => ['manage_projects', 'project_overview', 'project_planning'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'manage_projects' => [
            'name' => 'Manage Projects',
            'description' => 'Administrative project list for editing, lifecycle updates, and account-scoped project management.',
            'help' => 'Help users locate projects, apply filters, and execute project-level admin actions.',
            'actions' => ['Search/filter projects', 'Edit project settings', 'Archive or close projects'],
            'supporting_pages' => ['project_overview', 'archived_projects', 'project_planning'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'archived_projects' => [
            'name' => 'Archived Projects',
            'description' => 'Historical list of archived/completed projects and related records.',
            'help' => 'Explain archive state, retrieval behavior, and what actions are still allowed for archived records.',
            'actions' => ['Review archived projects', 'Open archived details', 'Delete archive records (authorized roles)'],
            'supporting_pages' => ['manage_projects', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'project_planning' => [
            'name' => 'Project Planning',
            'description' => 'Planning workspace for building and managing project delivery projections.',
            'help' => 'Clarify planning states and guide users from rough plan to executable delivery plan.',
            'actions' => ['Create/edit planning scenarios', 'Set primary delivery plan', 'Compare plan states'],
            'supporting_pages' => ['anticipated_deliveries', 'project_overview', 'module_cost_analysis'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'anticipated_deliveries' => [
            'name' => 'Anticipated Deliveries',
            'description' => 'Detailed route and delivery projection builder with timeline and cost modeling.',
            'help' => 'Explain stops/legs, projected costs, and how scenario changes affect delivery plan outcomes.',
            'actions' => ['Build route scenarios', 'Adjust legs and timing', 'Review projected cost tables'],
            'supporting_pages' => ['project_planning', 'project_overview', 'module_cost_analysis'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'admin_project_forecast' => [
            'name' => 'Admin Project Forecast',
            'description' => 'Global forecasting page for cross-project forecasted cost rollups.',
            'help' => 'Summarize forecast logic and compare forecasted values across projects/accounts.',
            'actions' => ['Review forecast totals', 'Inspect project-level forecast data'],
            'supporting_pages' => ['module_cost_analysis', 'accounting', 'dashboard'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'project_site' => [
            'name' => 'Link Project to Site',
            'description' => 'Administrative linking tool between project records and site records.',
            'help' => 'Explain site-to-project linkage and downstream effects on scheduling/logistics views.',
            'actions' => ['Link site to project', 'Review existing mappings'],
            'supporting_pages' => ['add_project', 'scheduling', 'project_overview'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'module_cost_analysis' => [
            'name' => 'Module Cost Analysis',
            'description' => 'Cost and value analysis across projects/modules, including logistics cost context.',
            'help' => 'Break down cost categories and clarify differences between logistics costs and module values.',
            'actions' => ['Review project cost metrics', 'Filter by project', 'Compare logistics cost components'],
            'supporting_pages' => ['project_overview', 'invoices_all', 'accounting'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'sustainability_overview' => [
            'name' => 'Sustainability Overview',
            'description' => 'Domestic content and sustainability reporting across portfolio/project data.',
            'help' => 'Explain domestic content metrics and help users interpret compliance-oriented trends.',
            'actions' => ['Review domestic content metrics', 'Analyze project/batch sustainability trends'],
            'supporting_pages' => ['modules', 'module_overview', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'modules' => [
            'name' => 'Manage Modules',
            'description' => 'Module batch list with project assignment and palletization status.',
            'help' => 'Help users find batches, understand status, and route to the correct next action.',
            'actions' => ['Browse/filter batches', 'Open batch detail', 'Manage batch records (authorized roles)'],
            'supporting_pages' => ['add_module_batch', 'module_overview', 'module_movements', 'manage_pallets'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'add_module_batch' => [
            'name' => 'Add Module Batch',
            'description' => 'Batch onboarding page for manufacturer, project assignment, wattage/quantity, and metadata.',
            'help' => 'Guide users through required fields and explain how this data drives palletization and shipment readiness.',
            'actions' => ['Create new module batches', 'Assign to projects', 'Define wattage/quantity rows'],
            'supporting_pages' => ['modules', 'module_overview', 'manufacturers'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'module_overview' => [
            'name' => 'Module Overview',
            'description' => 'Detailed module batch page including pallet generation, specs, and related logistics context.',
            'help' => 'Explain palletization state and batch-level logistics readiness.',
            'actions' => ['Inspect batch detail', 'Generate/undo pallets', 'Update batch fields (authorized roles)'],
            'supporting_pages' => ['modules', 'manage_pallets', 'create_shipment', 'module_movements'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'module_movements' => [
            'name' => 'Module Movements',
            'description' => 'Movement history and status transitions for pallets/modules across the logistics chain.',
            'help' => 'Trace where modules are now, what state they are in, and what transition happened last.',
            'actions' => ['Track movement history', 'Filter by project/status', 'Inspect pallet-level movement details'],
            'supporting_pages' => ['pallet_details', 'project_overview', 'warehouse'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'manage_pallets' => [
            'name' => 'Manage Pallets',
            'description' => 'Pallet inventory browser for status, assignment, and movement-ready context.',
            'help' => 'Help users locate pallets quickly and explain what current status means for next steps.',
            'actions' => ['Search/filter pallets', 'Open pallet details', 'Review assignment and movement status'],
            'supporting_pages' => ['pallet_details', 'module_overview', 'create_shipment', 'module_movements'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'pallet_details' => [
            'name' => 'Pallet Details',
            'description' => 'Single-pallet detail view with status, location history, and shipment linkage.',
            'help' => 'Explain pallet status and the last known movement/shipment context.',
            'actions' => ['Review pallet metadata', 'Trace movement history', 'Open related shipment/project pages'],
            'supporting_pages' => ['module_movements', 'manage_pallets', 'create_shipment'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'create_shipment' => [
            'name' => 'Create Shipment',
            'description' => 'Shipment creation and planning page for domestic and containerized logistics flows.',
            'help' => 'Explain shipment modes, BOL fields, and cost fields; guide users to valid next actions.',
            'actions' => ['Select eligible pallets', 'Build shipment', 'Set carrier/BOL/cost details'],
            'supporting_pages' => ['manage_pallets', 'manage_deliveries', 'container_tracking', 'generate_bol'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['shipment_workspace'],
        ],
        'manage_deliveries' => [
            'name' => 'Manage Deliveries',
            'description' => 'Legacy delivery route that now forwards into the unified project delivery tracker.',
            'help' => 'Guide users to delivery records and clarify that this route redirects to project-centric delivery tracking.',
            'actions' => ['Open delivery tracker context', 'Navigate to delivery scheduling/edit flows'],
            'supporting_pages' => ['view_project', 'scheduling', 'pods'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'container_tracking' => [
            'name' => 'Container Tracking',
            'description' => 'Container ETA tracking and milestone monitoring for in-transit shipments.',
            'help' => 'Summarize ETA status, identify late containers, and explain next operational follow-up.',
            'actions' => ['Review container timeline', 'Track ETA changes', 'Update tracking details (authorized roles)'],
            'supporting_pages' => ['create_shipment', 'manage_deliveries', 'warehouse'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'scheduling' => [
            'name' => 'Scheduling',
            'description' => 'Delivery appointment scheduling and update workflow for project deliveries.',
            'help' => 'Guide scheduling changes, explain delivery status implications, and clarify POD workflow dependencies.',
            'actions' => ['Schedule/reschedule deliveries', 'Manage delivery appointment details', 'Mark delivery outcomes'],
            'supporting_pages' => ['manage_deliveries', 'pods', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'bills_of_lading' => [
            'name' => 'Bills of Lading',
            'description' => 'BOL index with shipment linkage and document retrieval.',
            'help' => 'Help users locate BOL records and understand how BOLs tie to shipment lifecycle.',
            'actions' => ['Search BOL records', 'Open linked shipment/project data', 'Download BOL documents'],
            'supporting_pages' => ['create_shipment', 'manage_deliveries', 'pods'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'pods' => [
            'name' => 'Proof of Delivery',
            'description' => 'POD listing and upload status page for completed/attempted deliveries.',
            'help' => 'Explain missing POD follow-up and how POD status affects delivery completeness.',
            'actions' => ['Review POD coverage', 'Locate missing PODs', 'Download POD documents'],
            'supporting_pages' => ['scheduling', 'manage_deliveries', 'global_documents'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'ftd' => [
            'name' => 'Flash Test Data',
            'description' => 'Manufacturer flash-test reporting and QC document visibility.',
            'help' => 'Explain flash test purpose and assist with finding batch-level QC data.',
            'actions' => ['Review flash test records', 'Filter by project/batch', 'Download related data'],
            'supporting_pages' => ['module_overview', 'global_documents', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'freight_estimate' => [
            'name' => 'Freight Estimate',
            'description' => 'User-accessible freight quote request and estimate tracking page.',
            'help' => 'Explain estimate assumptions and guide users through quote request and follow-up flow.',
            'actions' => ['Create freight estimate requests', 'Review saved estimates', 'Track estimate status'],
            'supporting_pages' => ['admin_freight_estimates', 'create_shipment', 'module_cost_analysis'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'admin_freight_estimates' => [
            'name' => 'Admin Freight Estimates',
            'description' => 'Administrative freight estimator and quote management queue.',
            'help' => 'Help admins review requests, estimate outcomes, and move estimates through approval/response flow.',
            'actions' => ['Review freight requests', 'Respond with quotes', 'Manage estimate pipeline'],
            'supporting_pages' => ['freight_estimate', 'create_shipment', 'module_cost_analysis'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'generate_bol' => [
            'name' => 'Generate BOL',
            'description' => 'BOL document generation page tied to shipment records.',
            'help' => 'Guide users through BOL generation inputs and output usage.',
            'actions' => ['Generate BOL document', 'Review delivery shipment data before generation'],
            'supporting_pages' => ['create_shipment', 'bills_of_lading', 'global_documents'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'warehousing_overview' => [
            'name' => 'Warehousing Overview',
            'description' => 'Portfolio warehouse/port summary with inventory and throughput insights.',
            'help' => 'Explain facility utilization, inbound/outbound patterns, and routing to facility detail.',
            'actions' => ['Compare facilities', 'Review inventory posture', 'Open facility inventory detail'],
            'supporting_pages' => ['warehouse', 'cost_estimate_calculator', 'warehouse_optimization', 'warehouse_estimate'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'warehouse' => [
            'name' => 'Warehouse Inventory',
            'description' => 'Facility-level inventory, receiving, and movement management view for warehouses/ports.',
            'help' => 'Guide receiving flow, storage state interpretation, and movement actions for authorized roles.',
            'actions' => ['View inbound/outbound/in-storage pallets', 'Receive shipments', 'Manage pallet movements'],
            'supporting_pages' => ['warehousing_overview', 'create_shipment', 'module_movements', 'pods'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'add_warehouse' => [
            'name' => 'Add Warehouse',
            'description' => 'Warehouse/port setup form including facility details and fee structure.',
            'help' => 'Explain required setup fields and how fee structure affects warehousing cost calculations.',
            'actions' => ['Create facility requests/records', 'Define facility fee structure'],
            'supporting_pages' => ['warehousing_overview', 'warehouse', 'admin_warehouse_estimate'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'admin_warehouse_estimate' => [
            'name' => 'Admin Warehouse Estimate',
            'description' => 'Administrative warehouse quote management interface.',
            'help' => 'Help admins evaluate and manage warehouse quote requests and quote history.',
            'actions' => ['Review warehouse quote requests', 'Respond/manage quote records'],
            'supporting_pages' => ['warehouse_estimate', 'warehousing_overview', 'accounting'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'warehouse_estimate' => [
            'name' => 'Warehouse Estimate',
            'description' => 'User-facing warehouse quote request and estimate tracking page.',
            'help' => 'Clarify estimate inputs and expected response flow for warehouse quotes.',
            'actions' => ['Create warehouse quote requests', 'Track quote response status', 'Manage personal quote records'],
            'supporting_pages' => ['admin_warehouse_estimate', 'warehousing_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'cost_estimate_calculator' => [
            'name' => 'Cost Estimate Calculator',
            'description' => 'Interactive warehouse cost calculator with saved estimate scenarios.',
            'help' => 'Explain estimate assumptions and how to interpret calculated storage/logistics outputs.',
            'actions' => ['Create scenario estimates', 'Save/edit/delete personal calculator scenarios'],
            'supporting_pages' => ['warehousing_overview', 'warehouse_estimate', 'warehouse_optimization'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'warehouse_optimization' => [
            'name' => 'Warehouse Optimization',
            'description' => 'Scenario planning tool for optimizing warehouse strategy.',
            'help' => 'Guide users through scenario variables and interpretation of optimization tradeoffs.',
            'actions' => ['Build optimization scenarios', 'Save/edit personal optimization runs'],
            'supporting_pages' => ['cost_estimate_calculator', 'warehousing_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'manufacturer_overview' => [
            'name' => 'Manufacturer Overview',
            'description' => 'Manufacturer detail and relationship view tied to module batches and deliveries.',
            'help' => 'Explain manufacturer context and route to related modules/shipments.',
            'actions' => ['Review manufacturer details', 'Open related module batches and logistics records'],
            'supporting_pages' => ['manufacturers', 'add_manufacturer', 'modules'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'manufacturers' => [
            'name' => 'Manufacturers',
            'description' => 'Manufacturer management/request queue page.',
            'help' => 'Differentiate request behavior versus full management actions by role.',
            'actions' => ['Browse manufacturer list', 'Submit manufacturer requests', 'Manage manufacturer records (authorized roles)'],
            'supporting_pages' => ['manufacturer_overview', 'add_manufacturer', 'modules'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'No access.',
                'customer_admin' => 'Can submit and monitor manufacturer requests for account; limited direct edit/delete controls.',
                'admin' => 'Can review requests and manage manufacturer records for account scope.',
                'global_admin' => 'Can manage all manufacturers and requests globally.',
            ],
        ],
        'add_manufacturer' => [
            'name' => 'Add Manufacturer',
            'description' => 'Manufacturer onboarding/review form for new manufacturer records and request processing.',
            'help' => 'Guide role-appropriate workflow: request submission for customer admins, approval/creation for admins.',
            'actions' => ['Submit manufacturer request', 'Review/approve manufacturer requests', 'Create manufacturer records'],
            'supporting_pages' => ['manufacturers', 'manufacturer_overview'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'No access.',
                'customer_admin' => 'Can submit/request manufacturer additions for account approval workflow.',
                'admin' => 'Can create manufacturers and process account-scoped requests.',
                'global_admin' => 'Can create manufacturers and process requests across all accounts.',
            ],
        ],
        'documents' => [
            'name' => 'Project Documents',
            'description' => 'Project-first document browser for account-scoped logistics files.',
            'help' => 'Help users locate project-specific files and route to global document search when needed.',
            'actions' => ['Browse docs by project', 'Open/download linked files'],
            'supporting_pages' => ['global_documents', 'project_overview', 'pods', 'bills_of_lading'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['documents_workspace'],
        ],
        'global_documents' => [
            'name' => 'Global Documents',
            'description' => 'Cross-project document search, filter, upload, and bulk management page.',
            'help' => 'Guide filters, document category usage, and upload/download actions by role.',
            'actions' => ['Search/filter documents', 'Bulk download', 'Upload documents (authorized roles)'],
            'supporting_pages' => ['documents', 'bills_of_lading', 'pods', 'ftd'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['documents_workspace'],
        ],
        'project_photos' => [
            'name' => 'Project Photos',
            'description' => 'Project photo gallery for logistics progress, evidence, and issue documentation.',
            'help' => 'Explain upload/reorder flow and where photos are used in project operations.',
            'actions' => ['View photos', 'Upload/reorder photos (authorized roles)'],
            'supporting_pages' => ['project_overview', 'incident_reports', 'warranty'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'incident_reports' => [
            'name' => 'Incident Reports',
            'description' => 'Safety/incident tracking page for delivery and handling events.',
            'help' => 'Help users identify incident status and next action for follow-up.',
            'actions' => ['Review incidents', 'Inspect event details', 'Manage records (authorized roles)'],
            'supporting_pages' => ['scheduling', 'project_overview', 'project_photos'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'warranty' => [
            'name' => 'Warranty Claims',
            'description' => 'Warranty claim tracking and status management for module issues.',
            'help' => 'Explain claim states, filtering, and what follow-up steps are needed.',
            'actions' => ['Review claim status', 'Open claim details', 'Create/update claims (authorized roles)'],
            'supporting_pages' => ['warranty_create', 'warranty_detail', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'account_settings' => [
            'name' => 'Account Settings',
            'description' => 'User profile, password, and notification preference management.',
            'help' => 'Guide users through profile updates and notification settings.',
            'actions' => ['Update profile info', 'Change password', 'Adjust notification preferences'],
            'supporting_pages' => ['notifications', 'questions'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'Can manage own profile and notification settings.',
                'customer_admin' => 'Can manage own profile and notification settings.',
                'admin' => 'Can manage own profile and notification settings.',
                'global_admin' => 'Can manage own profile and notification settings.',
            ],
        ],
        'notifications' => [
            'name' => 'Notifications',
            'description' => 'In-app notification feed for logistics and portal events.',
            'help' => 'Clarify notification meaning and guide users to related pages for action.',
            'actions' => ['Review unread/read notifications', 'Navigate to linked records'],
            'supporting_pages' => ['account_settings', 'documents', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'Can manage own notifications only.',
                'customer_admin' => 'Can manage own notifications only.',
                'admin' => 'Can manage own notifications only.',
                'global_admin' => 'Can manage own notifications only.',
            ],
        ],
        'questions' => [
            'name' => 'Questions and Support',
            'description' => 'FAQ and support contact page for portal users.',
            'help' => 'Answer FAQ usage questions and help users file support requests with useful detail.',
            'actions' => ['Search FAQ', 'Submit support form'],
            'supporting_pages' => ['account_settings'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'Can search FAQ and submit support requests.',
                'customer_admin' => 'Can search FAQ and submit support requests.',
                'admin' => 'Can search FAQ and submit support requests.',
                'global_admin' => 'Can search FAQ and submit support requests.',
            ],
        ],
        'invoices_all' => [
            'name' => 'Invoices',
            'description' => 'Invoice listing and retrieval page for account-visible invoices.',
            'help' => 'Help users find invoices and understand what invoice scope they can see by role.',
            'actions' => ['Browse/filter invoices', 'Open/download invoice detail'],
            'supporting_pages' => ['module_cost_analysis', 'add_invoice', 'generate_invoice'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'add_invoice' => [
            'name' => 'Add Invoice',
            'description' => 'Global invoice entry/management page.',
            'help' => 'Explain invoice creation workflow and validation fields for financial records.',
            'actions' => ['Create invoices', 'Manage invoice records'],
            'supporting_pages' => ['invoices_all', 'generate_invoice', 'accounting'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'generate_invoice' => [
            'name' => 'Generate Invoice',
            'description' => 'Invoice document generation tool.',
            'help' => 'Guide invoice generation parameters and output behavior.',
            'actions' => ['Generate invoice outputs from logistics/accounting data'],
            'supporting_pages' => ['add_invoice', 'invoices_all', 'accounting'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'accounting' => [
            'name' => 'Accounting Overview',
            'description' => 'Global accounting workspace for financial rollups and operational accounting.',
            'help' => 'Summarize accounting metrics and route users to invoice/payables tools.',
            'actions' => ['Review accounting metrics', 'Open payables/invoice tools'],
            'supporting_pages' => ['add_invoice', 'accounts_payable', 'total_payables', 'generate_invoice'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'accounts_payable' => [
            'name' => 'Accounts Payable',
            'description' => 'Global AP workflow for payable generation and review.',
            'help' => 'Help interpret payable calculations and AP processing context.',
            'actions' => ['Generate payables', 'Review AP entries'],
            'supporting_pages' => ['accounting', 'total_payables'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'total_payables' => [
            'name' => 'Total Payables',
            'description' => 'Global aggregate payables summary page.',
            'help' => 'Explain total payable totals and where line-item detail originates.',
            'actions' => ['Review payable totals and aggregate breakdowns'],
            'supporting_pages' => ['accounts_payable', 'accounting'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'admin_management' => [
            'name' => 'Admin Management',
            'description' => 'Global user/account administration page.',
            'help' => 'Explain user/account management operations and role assignment implications.',
            'actions' => ['Manage users', 'Manage accounts', 'Manage invitations'],
            'supporting_pages' => ['account_settings'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'ddpm_overview' => [
            'name' => 'DDPm Overview (Legacy)',
            'description' => 'Legacy project overview page still used by historical DDPm workflows.',
            'help' => 'Explain this is a legacy overview and route users to the current project overview when appropriate.',
            'actions' => ['Review legacy project summary'],
            'supporting_pages' => ['project_overview', 'dashboard'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'ddpm_deliveries' => [
            'name' => 'DDPm Deliveries (Legacy)',
            'description' => 'Legacy delivery timeline/details page tied to older DDPm project flows.',
            'help' => 'Help users interpret legacy delivery info and direct them to unified delivery tracking when needed.',
            'actions' => ['Review legacy delivery status'],
            'supporting_pages' => ['view_project', 'manage_deliveries', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'accounts_payable_info' => [
            'name' => 'Accounts Payable Detail',
            'description' => 'Global-admin detail/review page for payable items and delivery finance adjustments.',
            'help' => 'Explain payable line-item logic and editing impact on aggregate totals.',
            'actions' => ['Review payable details', 'Adjust delivery financial fields'],
            'supporting_pages' => ['accounts_payable', 'accounting', 'total_payables'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'add_delivery' => [
            'name' => 'Add Delivery',
            'description' => 'Administrative form for creating delivery records linked to projects and facilities.',
            'help' => 'Guide delivery creation fields and validate destination/project context.',
            'actions' => ['Create delivery records', 'Set delivery logistics details'],
            'supporting_pages' => ['manage_deliveries', 'create_shipment', 'scheduling'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'add_manufacturer_location' => [
            'name' => 'Add Manufacturer Location',
            'description' => 'Manufacturer location onboarding/review page used for location requests and approvals.',
            'help' => 'Explain request-vs-approval behavior by role and required location metadata.',
            'actions' => ['Submit location requests', 'Approve/add manufacturer locations'],
            'supporting_pages' => ['manufacturer_locations', 'manufacturers', 'add_manufacturer'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'No access.',
                'customer_admin' => 'Can submit location requests for approval.',
                'admin' => 'Can review and manage location requests for account scope.',
                'global_admin' => 'Can review and manage location requests globally.',
            ],
        ],
        'admin_freight_estimate_view' => [
            'name' => 'Admin Freight Estimate Detail',
            'description' => 'Detailed administrative view for a single freight estimate request.',
            'help' => 'Help admins review estimate details and communicate/record quote outcomes.',
            'actions' => ['Inspect request detail', 'Update estimate response'],
            'supporting_pages' => ['admin_freight_estimates', 'freight_estimate'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'admin_login_attempts' => [
            'name' => 'Admin Login Attempts',
            'description' => 'Global-admin security page for reviewing authentication attempt history.',
            'help' => 'Explain login attempt data and potential security follow-up steps.',
            'actions' => ['Review login attempt history', 'Filter suspicious events'],
            'supporting_pages' => ['admin_management', 'account_settings'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'admin_warehouse_estimate_view' => [
            'name' => 'Admin Warehouse Estimate Detail',
            'description' => 'Detailed administrative view for a single warehouse quote request.',
            'help' => 'Help admins review quote specifics and manage response updates.',
            'actions' => ['Inspect quote detail', 'Respond/update quote'],
            'supporting_pages' => ['admin_warehouse_estimate', 'warehouse_estimate'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'assign_warehouse' => [
            'name' => 'Assign Warehouse (Legacy)',
            'description' => 'Legacy global-admin tool for linking warehouses to projects.',
            'help' => 'Explain this legacy linking flow and when modern warehouse/project pages should be used instead.',
            'actions' => ['Assign warehouse to project'],
            'supporting_pages' => ['warehousing_overview', 'warehouse', 'manage_projects'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'calculator_results' => [
            'name' => 'Calculator Results',
            'description' => 'Results page for warehouse cost calculator scenarios tied to the current user.',
            'help' => 'Explain cost totals and scenario result interpretation.',
            'actions' => ['Review scenario output', 'Save scenario results'],
            'supporting_pages' => ['cost_estimate_calculator', 'view_estimate'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'create_replacements' => [
            'name' => 'Create Replacements',
            'description' => 'Warranty admin workflow for creating replacement pallets/modules for claims.',
            'help' => 'Guide replacement creation logic and connection to existing warranty claims.',
            'actions' => ['Create replacement records', 'Link replacements to warranty claim'],
            'supporting_pages' => ['warranty', 'warranty_detail', 'warranty_create'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'edit_delivery' => [
            'name' => 'Edit Delivery',
            'description' => 'Administrative edit page for delivery records and delivery-linked details.',
            'help' => 'Guide safe delivery updates and clarify effect on downstream milestones/status.',
            'actions' => ['Update delivery fields', 'Adjust delivery-linked metadata'],
            'supporting_pages' => ['manage_deliveries', 'scheduling', 'pods'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'edit_future_project' => [
            'name' => 'Edit Future Project',
            'description' => 'Personal planning page for editing user-owned future forecast projects.',
            'help' => 'Explain forecast-project edit fields and linked estimate associations.',
            'actions' => ['Edit personal forecast project', 'Re-link forecast estimates'],
            'supporting_pages' => ['future_projects', 'future_projects_details', 'view_forecast'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'edit_invoice' => [
            'name' => 'Edit Invoice',
            'description' => 'Global-admin invoice edit page for updating invoice records.',
            'help' => 'Guide invoice field updates and validate invoice document updates.',
            'actions' => ['Edit invoice fields', 'Upload/replace invoice file'],
            'supporting_pages' => ['invoices_all', 'add_invoice', 'generate_invoice'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'edit_manufacturer' => [
            'name' => 'Edit Manufacturer',
            'description' => 'Administrative manufacturer profile editing page.',
            'help' => 'Help users update manufacturer information and understand request/approval context.',
            'actions' => ['Update manufacturer details', 'Adjust manufacturer profile data'],
            'supporting_pages' => ['manufacturers', 'manufacturer_overview', 'manufacturer_locations'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'No access.',
                'customer_admin' => 'Limited editing based on request flow/policy.',
                'admin' => 'Can edit manufacturer records in account scope.',
                'global_admin' => 'Can edit manufacturer records globally.',
            ],
        ],
        'edit_manufacturer_location' => [
            'name' => 'Edit Manufacturer Location',
            'description' => 'Administrative page for editing manufacturer location records.',
            'help' => 'Guide location updates and explain primary-location constraints.',
            'actions' => ['Edit manufacturer location details'],
            'supporting_pages' => ['manufacturer_locations', 'add_manufacturer_location'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'No access.',
                'customer_admin' => 'Limited edits based on request workflow.',
                'admin' => 'Can edit manufacturer locations in account scope.',
                'global_admin' => 'Can edit manufacturer locations globally.',
            ],
        ],
        'edit_module' => [
            'name' => 'Edit Module (Legacy Redirect)',
            'description' => 'Legacy module edit route that forwards to batch editing workflows.',
            'help' => 'Explain this route redirects to batch editor and guide users to modern editing pages.',
            'actions' => ['Open batch editor from legacy route'],
            'supporting_pages' => ['edit_module_batch', 'module_overview', 'modules'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'edit_module_batch' => [
            'name' => 'Edit Module Batch',
            'description' => 'Administrative editor for module batch details, allocations, and milestones.',
            'help' => 'Guide safe batch edits and explain effects on project and milestone data.',
            'actions' => ['Edit batch fields', 'Update allocation/milestone data'],
            'supporting_pages' => ['module_overview', 'modules', 'add_module_batch'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'edit_pallet' => [
            'name' => 'Edit Pallet',
            'description' => 'Administrative page for editing individual pallet records.',
            'help' => 'Explain pallet field updates and consistency implications for movements/shipments.',
            'actions' => ['Edit pallet metadata'],
            'supporting_pages' => ['pallet_details', 'manage_pallets', 'module_movements'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'edit_project' => [
            'name' => 'Edit Project',
            'description' => 'Administrative editor for project configuration and site constraints.',
            'help' => 'Guide project updates and explain impact on scheduling/logistics views.',
            'actions' => ['Edit project fields', 'Update site and project configuration'],
            'supporting_pages' => ['project_overview', 'manage_projects', 'project_planning'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'edit_warehouse' => [
            'name' => 'Edit Warehouse',
            'description' => 'Administrative editor for warehouse/port records and fee structures.',
            'help' => 'Guide facility updates and fee-structure changes safely.',
            'actions' => ['Edit warehouse details', 'Update fee structure'],
            'supporting_pages' => ['warehouse', 'warehousing_overview', 'add_warehouse'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'future_projects' => [
            'name' => 'Future Projects',
            'description' => 'Personal planning page listing user-owned future/forecast project records.',
            'help' => 'Explain personal forecast planning workflow and ownership scope.',
            'actions' => ['Create/view personal future projects'],
            'supporting_pages' => ['future_projects_details', 'edit_future_project', 'view_forecast'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'future_projects_details' => [
            'name' => 'Future Project Details',
            'description' => 'Detailed view for user-owned future forecast projects.',
            'help' => 'Guide users through forecast details and activation-request behavior.',
            'actions' => ['View/edit personal future project details'],
            'supporting_pages' => ['future_projects', 'edit_future_project', 'view_forecast'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'invoice_info' => [
            'name' => 'Invoice Info',
            'description' => 'Global-admin invoice generation/detail page with payable and cost breakdowns.',
            'help' => 'Explain generated invoice components and payable rollups.',
            'actions' => ['Review/generated invoice data', 'Export invoice output'],
            'supporting_pages' => ['generate_invoice', 'invoices_all', 'accounts_payable_info'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'invoices' => [
            'name' => 'Project Invoices (Legacy)',
            'description' => 'Project-specific invoice list page scoped by account access.',
            'help' => 'Help users interpret project invoice list and route to broader invoice views if needed.',
            'actions' => ['Browse project invoice history'],
            'supporting_pages' => ['invoices_all', 'project_overview', 'module_cost_analysis'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'link_pallet_deliveries' => [
            'name' => 'Link Pallets to Deliveries',
            'description' => 'Administrative workflow for linking pallets to delivery records, including CSV-assisted linking.',
            'help' => 'Guide linking steps and validation expectations for bulk operations.',
            'actions' => ['Link pallets to deliveries', 'Run CSV-based linking'],
            'supporting_pages' => ['manage_delivery_pallets', 'manage_deliveries', 'create_shipment'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'manage_delivery_pallets' => [
            'name' => 'Manage Delivery Pallets',
            'description' => 'Administrative pallet assignment page for a specific delivery.',
            'help' => 'Help users assign/unassign pallets and keep delivery quantities aligned.',
            'actions' => ['Assign pallets to delivery', 'Review delivery quantity alignment'],
            'supporting_pages' => ['link_pallet_deliveries', 'edit_delivery', 'manage_deliveries'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'manage_port_inventory' => [
            'name' => 'Manage Port Inventory',
            'description' => 'Administrative inventory/operations page specifically for port facilities.',
            'help' => 'Explain port-specific inventory and customs workflow context.',
            'actions' => ['Manage port inventory', 'Track customs-related status'],
            'supporting_pages' => ['warehouse', 'warehousing_overview', 'container_tracking'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'manufacturer_details' => [
            'name' => 'Manufacturer Details',
            'description' => 'Detailed analytics-style manufacturer page tied to modules and project access scope.',
            'help' => 'Explain manufacturer metrics and related project/module context.',
            'actions' => ['Review manufacturer metrics', 'Inspect project-linked manufacturer activity'],
            'supporting_pages' => ['manufacturer_overview', 'manufacturers', 'modules'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'manufacturer_locations' => [
            'name' => 'Manufacturer Locations',
            'description' => 'Location list/management page for manufacturer facilities.',
            'help' => 'Guide users through location records and request/approval constraints.',
            'actions' => ['Browse locations', 'Manage locations (authorized roles)'],
            'supporting_pages' => ['manufacturers', 'add_manufacturer_location', 'edit_manufacturer_location'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => [
                'user' => 'No access.',
                'customer_admin' => 'Can view and request location changes.',
                'admin' => 'Can manage locations in account scope.',
                'global_admin' => 'Can manage locations globally.',
            ],
        ],
        'modules_docs' => [
            'name' => 'Module Documents (Legacy)',
            'description' => 'Legacy project-scoped module document page.',
            'help' => 'Help users find module-related project documents and route to global documents if needed.',
            'actions' => ['Browse module-related project documents'],
            'supporting_pages' => ['project_documents', 'global_documents', 'module_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'project_close' => [
            'name' => 'Project Close-Out',
            'description' => 'Project close-out and export workflow with role-gated close/edit actions.',
            'help' => 'Explain close-out exports and clearly separate read/export vs close/edit permissions.',
            'actions' => ['Review close-out package', 'Export close-out artifacts', 'Close project (authorized roles)'],
            'supporting_pages' => ['project_overview', 'archived_projects', 'project_documents'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'project_cost_details' => [
            'name' => 'Project Cost Details',
            'description' => 'Detailed project cost breakdown page with account-scoped access checks.',
            'help' => 'Explain cost components and how detailed metrics map to summary reports.',
            'actions' => ['Review detailed project cost metrics'],
            'supporting_pages' => ['module_cost_analysis', 'project_overview', 'invoices_all'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'project_documents' => [
            'name' => 'Project Documents (Legacy)',
            'description' => 'Legacy project-level document explorer scoped by account membership.',
            'help' => 'Help users find docs in this legacy view and route to current document pages when appropriate.',
            'actions' => ['Browse project document folders', 'Download project documents'],
            'supporting_pages' => ['documents', 'global_documents', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['documents_workspace'],
        ],
        'project_information' => [
            'name' => 'Project Information',
            'description' => 'Project information/details page with role-based access to project metadata.',
            'help' => 'Explain project metadata fields and what users can inspect vs manage.',
            'actions' => ['Review project details'],
            'supporting_pages' => ['project_overview', 'manage_projects', 'edit_project'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'project_overview_backup' => [
            'name' => 'Project Overview Backup (Legacy)',
            'description' => 'Legacy backup version of project overview retained for fallback workflows.',
            'help' => 'Identify this as backup/legacy and direct users to primary project overview when possible.',
            'actions' => ['Review legacy project overview'],
            'supporting_pages' => ['project_overview', 'module_overview', 'create_shipment'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'project_safety' => [
            'name' => 'Project Safety',
            'description' => 'Project safety incident summary and timeline page.',
            'help' => 'Help users interpret incident trends and timeframe filters.',
            'actions' => ['Review project safety incidents by timeframe'],
            'supporting_pages' => ['incident_reports', 'project_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'project_sustainability_details' => [
            'name' => 'Project Sustainability Details',
            'description' => 'Detailed sustainability/domestic-content metrics for a single project.',
            'help' => 'Explain project-level sustainability calculations and interpretation.',
            'actions' => ['Review project sustainability metrics'],
            'supporting_pages' => ['sustainability_overview', 'project_overview', 'module_overview'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read'],
        ],
        'scenario_detail' => [
            'name' => 'Scenario Detail',
            'description' => 'Detailed planning scenario workspace for allocations, contracts, and activation flow.',
            'help' => 'Guide scenario interpretation and distinguish view-only vs editable actions by role/context.',
            'actions' => ['Review planning scenario', 'Edit scenario elements (authorized contexts)'],
            'supporting_pages' => ['project_planning', 'anticipated_deliveries', 'module_cost_analysis'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'upload_manufacturer_links' => [
            'name' => 'Upload Manufacturer Links',
            'description' => 'Administrative import workflow for mapping real manufacturer IDs to portal pallet records.',
            'help' => 'Guide mapping workflow steps and account-scope expectations.',
            'actions' => ['Upload mapping file', 'Map manufacturer IDs to pallets'],
            'supporting_pages' => ['upload_pallets', 'module_overview', 'manage_pallets'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'upload_manufacturer_schedule' => [
            'name' => 'Upload Manufacturer Schedule',
            'description' => 'Upload hub routing users to pallet and shipment import workflows.',
            'help' => 'Clarify which import path to choose based on desired outcome.',
            'actions' => ['Choose import path', 'Begin pallet or shipment import'],
            'supporting_pages' => ['upload_pallets', 'upload_shipments'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'upload_pallets' => [
            'name' => 'Upload Pallets',
            'description' => 'Administrative multi-step import for module/pallet inventory.',
            'help' => 'Guide mapping, validation, and confirmation for pallet import.',
            'actions' => ['Upload and map pallet file', 'Confirm pallet import'],
            'supporting_pages' => ['upload_manufacturer_schedule', 'module_overview', 'modules'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'upload_pod' => [
            'name' => 'Upload POD',
            'description' => 'Administrative POD upload workflow tied to delivery records.',
            'help' => 'Guide POD upload requirements and delivery linkage behavior.',
            'actions' => ['Upload POD document to delivery'],
            'supporting_pages' => ['pods', 'edit_delivery', 'manage_deliveries'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'upload_shipments' => [
            'name' => 'Upload Shipments',
            'description' => 'Administrative multi-step import for shipment/delivery records.',
            'help' => 'Guide shipment import mapping and validation before commit.',
            'actions' => ['Upload and map shipment file', 'Confirm shipment import'],
            'supporting_pages' => ['upload_manufacturer_schedule', 'manage_deliveries', 'create_shipment'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'view_estimate' => [
            'name' => 'View Cost Estimate',
            'description' => 'Read view for a user-owned warehouse calculator estimate.',
            'help' => 'Explain estimate totals and scenario details for the current user.',
            'actions' => ['Review saved estimate details'],
            'supporting_pages' => ['cost_estimate_calculator', 'calculator_results'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'view_forecast' => [
            'name' => 'View Forecast',
            'description' => 'Read view for a user-owned forecast scenario and linked estimates.',
            'help' => 'Explain forecast assumptions and linked estimate context.',
            'actions' => ['Review saved forecast details'],
            'supporting_pages' => ['future_projects', 'future_projects_details', 'edit_future_project'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'view_freight_estimate' => [
            'name' => 'View Freight Estimate',
            'description' => 'Read view for a user-owned freight estimate.',
            'help' => 'Explain freight estimate breakdown and assumptions.',
            'actions' => ['Review saved freight estimate'],
            'supporting_pages' => ['freight_estimate', 'admin_freight_estimates'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'view_project' => [
            'name' => 'Project Delivery Tracker',
            'description' => 'Unified project delivery tracker page for delivery operations and status management.',
            'help' => 'Guide delivery-tracker usage and clarify which actions are role-gated.',
            'actions' => ['Review project deliveries', 'Manage delivery workflow (authorized roles)'],
            'supporting_pages' => ['manage_deliveries', 'scheduling', 'pods', 'create_shipment'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
        'view_warehouse_estimate' => [
            'name' => 'View Warehouse Estimate',
            'description' => 'Read view for a user-owned warehouse quote response/estimate.',
            'help' => 'Explain quote details and attached document context.',
            'actions' => ['Review saved warehouse estimate details'],
            'supporting_pages' => ['warehouse_estimate', 'admin_warehouse_estimate'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_personal_workspace'],
        ],
        'warehouses' => [
            'name' => 'Warehouses (Legacy Global List)',
            'description' => 'Legacy global-admin list/summary page for all warehouse records.',
            'help' => 'Explain this legacy global list and direct users to current warehousing overview when applicable.',
            'actions' => ['Review global warehouse list'],
            'supporting_pages' => ['warehousing_overview', 'warehouse', 'add_warehouse'],
            'access_roles' => ['global_admin'],
            'role_capabilities' => $profiles['global_only'],
        ],
        'warranty_create' => [
            'name' => 'Create Warranty Claim',
            'description' => 'Administrative workflow for creating warranty claims.',
            'help' => 'Guide claim creation requirements and project/scheduling linkage.',
            'actions' => ['Create warranty claim'],
            'supporting_pages' => ['warranty', 'warranty_detail', 'create_replacements'],
            'access_roles' => ['customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['account_admins_only'],
        ],
        'warranty_detail' => [
            'name' => 'Warranty Claim Detail',
            'description' => 'Detailed warranty claim page with project-scoped authorization checks.',
            'help' => 'Explain claim detail fields, event history, and role-specific actions.',
            'actions' => ['Review claim details', 'Manage claim updates (authorized roles)'],
            'supporting_pages' => ['warranty', 'warranty_create', 'create_replacements'],
            'access_roles' => ['user', 'customer_admin', 'admin', 'global_admin'],
            'role_capabilities' => $profiles['all_read_with_admin_actions'],
        ],
    ],
];
